name: Release

on:
  workflow_dispatch:
    inputs:
      run:
        description: 'The Package workflow run to release'
        required: true
      dry-run:
        description: 'If true, the workflow only indicates which artifacts would be uploaded'
        required: true
        type: boolean
        default: 'true'

jobs:
  psgallery-release:
    name: PSGallery release
    runs-on: windows-2022
    environment: build-and-publish

    steps:
      - name: Check out ${{ github.repository }}
        uses: actions/checkout@v2

      - name: Download artifacts
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.DEVOLUTIONSBOT_TOKEN }}
        run: gh run download ${{ github.event.inputs.run }} -n pwsh-module --repo $Env:GITHUB_REPOSITORY

      - name: Publish PowerShell module
        shell: pwsh
        run: |
          $DryRun = [System.Convert]::ToBoolean('${{ github.event.inputs.dry-run }}')
          $PackageFile = (Get-ChildItem Devolutions.Authenticode.*.nupkg).FullName
          $NugetApiKey = '${{ secrets.PS_GALLERY_NUGET_API_KEY }}'
          $NugetPushUrl = 'https://www.powershellgallery.com/api/v2/package'
          
          if (-Not $DryRun) {
            & nuget.exe push $PackageFile -Source $NugetPushUrl -ApiKey $NugetApiKey
          }
